import { z } from "zod";

const categoryEnum = [
  "Gemstone",
  "Jewellery",
  "Watch",
  "Custom Product",
  "Accessory",
  "Ring",
  "Necklace",
  "Earrings",
  "Bracelet",
  "Pendant",
  "Other",
];

const statusEnum = [
  "Draft",
  "Available",
  "Reserved",
  "On Consignment",
  "On Memo",
  "In Production",
  "Sold",
  "Returned",
  "Archived",
  "In Stock",
  "Missing",
  "Damaged",
];

export const productSchema = z.object({
  stockNo: z.string().trim().min(1, "Stock number is required"),
  category: z.enum(categoryEnum).default("Other"),
  name: z.string().trim().min(1, "Product name is required"),
  sku: z.string().optional().or(z.literal("")),
  barcode: z.string().optional().or(z.literal("")),
  qrCode: z.string().optional().or(z.literal("")),
  subCategory: z.string().optional().or(z.literal("")),
  collection: z.string().optional().or(z.literal("")),
  brand: z.string().optional().or(z.literal("")),
  model: z.string().optional().or(z.literal("")),
  description: z.string().trim().optional().or(z.literal("")),
  shortDescription: z.string().trim().optional().or(z.literal("")),
  sellingPrice: z.coerce.number().min(0, "Selling price must be positive"),
  costPrice: z.coerce.number().min(0, "Cost price must be positive"),
  purchasePrice: z.coerce.number().min(0).optional().default(0),
  additionalCost: z.coerce.number().min(0).optional().default(0),
  totalCost: z.coerce.number().min(0).optional().default(0),
  minimumSellingPrice: z.coerce.number().min(0).optional().default(0),
  wholesalePrice: z.coerce.number().min(0).optional().default(0),
  retailPrice: z.coerce.number().min(0).optional().default(0),
  currency: z.string().optional().default("USD"),
  discountAllowed: z.enum(["true", "false"]).optional().default("false"),
  profit: z.coerce.number().min(0).optional().default(0),
  margin: z.coerce.number().min(0).optional().default(0),
  weight: z.string().optional().or(z.literal("")),
  dimensions: z.string().optional().or(z.literal("")),
  material: z.string().optional().or(z.literal("")),
  metalType: z.string().optional().or(z.literal("")),
  goldPurity: z.string().optional().or(z.literal("")),
  countryOfOrigin: z.string().optional().or(z.literal("")),
  manufacturedBy: z.string().optional().or(z.literal("")),
  manufacturedDate: z.string().optional().or(z.literal("")),
  gemstoneType: z.string().optional().or(z.literal("")),
  variety: z.string().optional().or(z.literal("")),
  origin: z.string().optional().or(z.literal("")),
  shape: z.string().optional().or(z.literal("")),
  cut: z.string().optional().or(z.literal("")),
  colour: z.string().optional().or(z.literal("")),
  clarity: z.string().optional().or(z.literal("")),
  treatment: z.string().optional().or(z.literal("")),
  heatStatus: z.string().optional().or(z.literal("")),
  oilLevel: z.string().optional().or(z.literal("")),
  transparency: z.string().optional().or(z.literal("")),
  qualityGrade: z.string().optional().or(z.literal("")),
  naturalSynthetic: z.string().optional().or(z.literal("")),
  pieces: z.coerce.number().min(0).optional().default(0),
  totalCarat: z.coerce.number().min(0).optional().default(0),
  averageCarat: z.coerce.number().min(0).optional().default(0),
  costPerCarat: z.coerce.number().min(0).optional().default(0),
  sellingPricePerCarat: z.coerce.number().min(0).optional().default(0),
  certificateAvailable: z.enum(["true", "false"]).optional().default("false"),
  laboratory: z.string().optional().or(z.literal("")),
  certificateNumber: z.string().optional().or(z.literal("")),
  certificateDate: z.string().optional().or(z.literal("")),
  certificateCost: z.coerce.number().min(0).optional().default(0),
  certificatePdf: z.string().optional().or(z.literal("")),
  certificateImages: z.string().optional().or(z.literal("")),
  certificateNotes: z.string().optional().or(z.literal("")),
  materialCost: z.coerce.number().min(0).optional().default(0),
  manufacturingCost: z.coerce.number().min(0).optional().default(0),
  packagingCost: z.coerce.number().min(0).optional().default(0),
  shippingCost: z.coerce.number().min(0).optional().default(0),
  insuranceCost: z.coerce.number().min(0).optional().default(0),
  otherCosts: z.coerce.number().min(0).optional().default(0),
  totalCostSummary: z.coerce.number().min(0).optional().default(0),
  warehouse: z.string().optional().or(z.literal("")),
  location: z.string().optional().or(z.literal("")),
  shelf: z.string().optional().or(z.literal("")),
  quantity: z.coerce.number().min(0).optional().default(0),
  availableQuantity: z.coerce.number().min(0).optional().default(0),
  reservedQuantity: z.coerce.number().min(0).optional().default(0),
  minimumStock: z.coerce.number().min(0).optional().default(0),
  maximumStock: z.coerce.number().min(0).optional().default(0),
  reorderLevel: z.coerce.number().min(0).optional().default(0),
  supplier: z.string().optional().or(z.literal("")),
  supplierReference: z.string().optional().or(z.literal("")),
  purchaseDate: z.string().optional().or(z.literal("")),
  purchaseInvoice: z.string().optional().or(z.literal("")),
  paymentStatus: z.string().optional().or(z.literal("")),
  outstandingAmount: z.coerce.number().min(0).optional().default(0),
  supplierNotes: z.string().optional().or(z.literal("")),
  sellingStatus: z.string().optional().or(z.literal("")),
  lastSellingPrice: z.coerce.number().min(0).optional().default(0),
  customer: z.string().optional().or(z.literal("")),
  salesperson: z.string().optional().or(z.literal("")),
  lastSoldDate: z.string().optional().or(z.literal("")),
  salesPaymentStatus: z.string().optional().or(z.literal("")),
  consignmentStatus: z.string().optional().or(z.literal("")),
  documents: z.string().optional().or(z.literal("")),
  warranty: z.string().optional().or(z.literal("")),
  cadFiles: z.string().optional().or(z.literal("")),
  videos: z.string().optional().or(z.literal("")),
  internalNotes: z.string().optional().or(z.literal("")),
  customerNotes: z.string().optional().or(z.literal("")),
  specialInstructions: z.string().optional().or(z.literal("")),
  tagsInput: z.string().optional().default(""),
  components: z.array(z.object({ name: z.string().optional().or(z.literal("")), quantity: z.coerce.number().min(0).default(1), unitCost: z.coerce.number().min(0).default(0) })).optional().default([]),
  status: z.enum(statusEnum).default("Draft"),
  imageUrls: z.array(z.string()).optional().default([]),
});

export const componentSchema = z.object({
  sourceType: z.enum(["Gemstone", "GemstoneLot", "Material"]),
  sourceId: z.string().min(1, "Source item is required"),
  quantity: z.coerce.number().min(0, "Quantity must be positive"),
  weight: z.coerce.number().min(0, "Weight must be positive"),
  remarks: z.string().trim().optional().or(z.literal("")),
});
