import { z } from "zod";

const categoryEnum = [
  "Gemstone",
  "Jewellery",
  "Watch",
  "Custom Product",
  "Accessory",
  "Ring",
  "Necklace",
  "Earrings",
  "Bracelet",
  "Pendant",
  "Other",
];

const statusEnum = [
  "Draft",
  "Available",
  "Reserved",
  "On Consignment",
  "On Memo",
  "In Production",
  "Sold",
  "Returned",
  "Archived",
  "In Stock",
  "Missing",
  "Damaged",
];

const coerceNum = (val) => {
  if (val === "" || val === null || val === undefined || isNaN(val)) return 0;
  return Number(val);
};

const coerceDateString = (val) => {
  if (!val) return "";
  if (typeof val === "string") return val.slice(0, 10);
  if (val instanceof Date) return val.toISOString().slice(0, 10);
  if (typeof val === "object" && val?.target?.value !== undefined) {
    return String(val.target.value || "").slice(0, 10);
  }
  return String(val).slice(0, 10);
};

export const productSchema = z.object({
  stockNo: z.string().trim().optional().or(z.literal("")),
  category: z.enum(categoryEnum).optional().default("Other"),
  name: z.string().trim().optional().or(z.literal("")),
  sku: z.string().optional().or(z.literal("")),
  barcode: z.string().optional().or(z.literal("")),
  qrCode: z.string().optional().or(z.literal("")),
  subCategory: z.string().optional().or(z.literal("")),
  collection: z.string().optional().or(z.literal("")),
  brand: z.string().optional().or(z.literal("")),
  model: z.string().optional().or(z.literal("")),
  description: z.string().trim().optional().or(z.literal("")),
  shortDescription: z.string().trim().optional().or(z.literal("")),
  sellingPrice: z.preprocess(coerceNum, z.number().optional().default(0)),
  costPrice: z.preprocess(coerceNum, z.number().optional().default(0)),
  purchasePrice: z.preprocess(coerceNum, z.number().optional().default(0)),
  additionalCost: z.preprocess(coerceNum, z.number().optional().default(0)),
  totalCost: z.preprocess(coerceNum, z.number().optional().default(0)),
  minimumSellingPrice: z.preprocess(coerceNum, z.number().optional().default(0)),
  wholesalePrice: z.preprocess(coerceNum, z.number().optional().default(0)),
  retailPrice: z.preprocess(coerceNum, z.number().optional().default(0)),
  currency: z.string().optional().default("USD"),
  discountAllowed: z.union([z.boolean(), z.enum(["true", "false"])]).optional().default(false),
  profit: z.preprocess(coerceNum, z.number().optional().default(0)),
  margin: z.preprocess(coerceNum, z.number().optional().default(0)),
  weight: z.string().optional().or(z.literal("")),
  dimensions: z.string().optional().or(z.literal("")),
  material: z.string().optional().or(z.literal("")),
  metalType: z.string().optional().or(z.literal("")),
  goldPurity: z.string().optional().or(z.literal("")),
  countryOfOrigin: z.string().optional().or(z.literal("")),
  manufacturedBy: z.string().optional().or(z.literal("")),
  manufacturedDate: z.preprocess(coerceDateString, z.string().optional().or(z.literal(""))),
  gemstoneType: z.string().optional().or(z.literal("")),
  variety: z.string().optional().or(z.literal("")),
  origin: z.string().optional().or(z.literal("")),
  shape: z.string().optional().or(z.literal("")),
  cut: z.string().optional().or(z.literal("")),
  colour: z.string().optional().or(z.literal("")),
  clarity: z.string().optional().or(z.literal("")),
  treatment: z.string().optional().or(z.literal("")),
  heatStatus: z.string().optional().or(z.literal("")),
  oilLevel: z.string().optional().or(z.literal("")),
  transparency: z.string().optional().or(z.literal("")),
  qualityGrade: z.string().optional().or(z.literal("")),
  naturalSynthetic: z.string().optional().or(z.literal("")),
  pieces: z.preprocess(coerceNum, z.number().optional().default(0)),
  totalCarat: z.preprocess(coerceNum, z.number().optional().default(0)),
  averageCarat: z.preprocess(coerceNum, z.number().optional().default(0)),
  costPerCarat: z.preprocess(coerceNum, z.number().optional().default(0)),
  sellingPricePerCarat: z.preprocess(coerceNum, z.number().optional().default(0)),
  certificateAvailable: z.union([z.boolean(), z.enum(["true", "false"])]).optional().default(false),
  laboratory: z.string().optional().or(z.literal("")),
  certificateNumber: z.string().optional().or(z.literal("")),
  certificateDate: z.preprocess(coerceDateString, z.string().optional().or(z.literal(""))),
  certificateCost: z.preprocess(coerceNum, z.number().optional().default(0)),
  certificatePdf: z.string().optional().or(z.literal("")),
  certificateImages: z.string().optional().or(z.literal("")),
  certificateNotes: z.string().optional().or(z.literal("")),
  materialCost: z.preprocess(coerceNum, z.number().optional().default(0)),
  manufacturingCost: z.preprocess(coerceNum, z.number().optional().default(0)),
  packagingCost: z.preprocess(coerceNum, z.number().optional().default(0)),
  shippingCost: z.preprocess(coerceNum, z.number().optional().default(0)),
  insuranceCost: z.preprocess(coerceNum, z.number().optional().default(0)),
  otherCosts: z.preprocess(coerceNum, z.number().optional().default(0)),
  totalCostSummary: z.preprocess(coerceNum, z.number().optional().default(0)),
  warehouse: z.string().optional().or(z.literal("")),
  location: z.string().optional().or(z.literal("")),
  shelf: z.string().optional().or(z.literal("")),
  quantity: z.preprocess(coerceNum, z.number().optional().default(0)),
  availableQuantity: z.preprocess(coerceNum, z.number().optional().default(0)),
  reservedQuantity: z.preprocess(coerceNum, z.number().optional().default(0)),
  minimumStock: z.preprocess(coerceNum, z.number().optional().default(0)),
  maximumStock: z.preprocess(coerceNum, z.number().optional().default(0)),
  reorderLevel: z.preprocess(coerceNum, z.number().optional().default(0)),
  supplier: z.string().optional().or(z.literal("")),
  supplierReference: z.string().optional().or(z.literal("")),
  purchaseDate: z.preprocess(coerceDateString, z.string().optional().or(z.literal(""))),
  purchaseInvoice: z.string().optional().or(z.literal("")),
  paymentStatus: z.string().optional().or(z.literal("")),
  outstandingAmount: z.preprocess(coerceNum, z.number().optional().default(0)),
  supplierNotes: z.string().optional().or(z.literal("")),
  sellingStatus: z.string().optional().or(z.literal("")),
  lastSellingPrice: z.preprocess(coerceNum, z.number().optional().default(0)),
  customer: z.string().optional().or(z.literal("")),
  salesperson: z.string().optional().or(z.literal("")),
  lastSoldDate: z.preprocess(coerceDateString, z.string().optional().or(z.literal(""))),
  salesPaymentStatus: z.string().optional().or(z.literal("")),
  consignmentStatus: z.string().optional().or(z.literal("")),
  documents: z.string().optional().or(z.literal("")),
  warranty: z.string().optional().or(z.literal("")),
  cadFiles: z.string().optional().or(z.literal("")),
  videos: z.string().optional().or(z.literal("")),
  internalNotes: z.string().optional().or(z.literal("")),
  customerNotes: z.string().optional().or(z.literal("")),
  specialInstructions: z.string().optional().or(z.literal("")),
  tagsInput: z.string().optional().default(""),
  tags: z.array(z.string()).optional().default([]),
  components: z.array(
    z.object({
      name: z.string().optional().or(z.literal("")),
      quantity: z.preprocess(coerceNum, z.number().default(1)),
      unitCost: z.preprocess(coerceNum, z.number().default(0)),
    })
  ).optional().default([]),
  status: z.enum(statusEnum).default("Draft"),
  imageUrls: z.array(z.string()).optional().default([]),
});

export const componentSchema = z.object({
  sourceType: z.enum(["Gemstone", "GemstoneLot", "Material"]),
  sourceId: z.string().min(1, "Source item is required"),
  quantity: z.preprocess(coerceNum, z.number().min(0, "Quantity must be positive")),
  weight: z.preprocess(coerceNum, z.number().min(0, "Weight must be positive")),
  remarks: z.string().trim().optional().or(z.literal("")),
});
