import mongoose from "mongoose";

const { Schema } = mongoose;

const productSchema = new Schema(
  {
    productCode: {
      type: String,
      required: true,
      unique: true,
      trim: true,
    },
    stockNo: {
      type: String,
      required: true,
      trim: true,
    },
    category: {
      type: String,
      required: [true, "Product category is required"],
      enum: [
        "Gemstone",
        "Jewellery",
        "Watch",
        "Custom Product",
        "Accessory",
        "Ring",
        "Necklace",
        "Earrings",
        "Bracelet",
        "Pendant",
        "Other",
      ],
      default: "Other",
    },
    name: {
      type: String,
      required: [true, "Product name is required"],
      trim: true,
    },
    sku: { type: String, default: "" },
    barcode: { type: String, default: "" },
    qrCode: { type: String, default: "" },
    subCategory: { type: String, default: "" },
    collection: { type: String, default: "" },
    brand: { type: String, default: "" },
    model: { type: String, default: "" },
    description: { type: String, default: "" },
    shortDescription: { type: String, default: "" },
    sellingPrice: {
      type: Number,
      required: [true, "Selling price is required"],
      min: 0,
      default: 0,
    },
    costPrice: {
      type: Number,
      required: [true, "Cost price is required"],
      min: 0,
      default: 0,
    },
    purchasePrice: { type: Number, default: 0 },
    additionalCost: { type: Number, default: 0 },
    totalCost: { type: Number, default: 0 },
    minimumSellingPrice: { type: Number, default: 0 },
    wholesalePrice: { type: Number, default: 0 },
    retailPrice: { type: Number, default: 0 },
    currency: { type: String, default: "USD" },
    discountAllowed: { type: Boolean, default: false },
    profit: { type: Number, default: 0 },
    margin: { type: Number, default: 0 },
    weight: { type: String, default: "" },
    dimensions: { type: String, default: "" },
    material: { type: String, default: "" },
    metalType: { type: String, default: "" },
    goldPurity: { type: String, default: "" },
    countryOfOrigin: { type: String, default: "" },
    manufacturedBy: { type: String, default: "" },
    manufacturedDate: { type: String, default: "" },
    gemstoneType: { type: String, default: "" },
    variety: { type: String, default: "" },
    origin: { type: String, default: "" },
    shape: { type: String, default: "" },
    cut: { type: String, default: "" },
    colour: { type: String, default: "" },
    clarity: { type: String, default: "" },
    treatment: { type: String, default: "" },
    heatStatus: { type: String, default: "" },
    oilLevel: { type: String, default: "" },
    transparency: { type: String, default: "" },
    qualityGrade: { type: String, default: "" },
    naturalSynthetic: { type: String, default: "" },
    pieces: { type: Number, default: 0 },
    totalCarat: { type: Number, default: 0 },
    averageCarat: { type: Number, default: 0 },
    costPerCarat: { type: Number, default: 0 },
    sellingPricePerCarat: { type: Number, default: 0 },
    certificateAvailable: { type: Boolean, default: false },
    laboratory: { type: String, default: "" },
    certificateNumber: { type: String, default: "" },
    certificateDate: { type: String, default: "" },
    certificateCost: { type: Number, default: 0 },
    certificatePdf: { type: String, default: "" },
    certificateImages: { type: String, default: "" },
    certificateNotes: { type: String, default: "" },
    materialCost: { type: Number, default: 0 },
    manufacturingCost: { type: Number, default: 0 },
    packagingCost: { type: Number, default: 0 },
    shippingCost: { type: Number, default: 0 },
    insuranceCost: { type: Number, default: 0 },
    otherCosts: { type: Number, default: 0 },
    totalCostSummary: { type: Number, default: 0 },
    warehouse: { type: String, default: "" },
    location: { type: String, default: "" },
    shelf: { type: String, default: "" },
    quantity: { type: Number, default: 0 },
    availableQuantity: { type: Number, default: 0 },
    reservedQuantity: { type: Number, default: 0 },
    minimumStock: { type: Number, default: 0 },
    maximumStock: { type: Number, default: 0 },
    reorderLevel: { type: Number, default: 0 },
    supplier: { type: String, default: "" },
    supplierReference: { type: String, default: "" },
    purchaseDate: { type: String, default: "" },
    purchaseInvoice: { type: String, default: "" },
    paymentStatus: { type: String, default: "" },
    outstandingAmount: { type: Number, default: 0 },
    supplierNotes: { type: String, default: "" },
    sellingStatus: { type: String, default: "" },
    lastSellingPrice: { type: Number, default: 0 },
    customer: { type: String, default: "" },
    salesperson: { type: String, default: "" },
    lastSoldDate: { type: String, default: "" },
    salesPaymentStatus: { type: String, default: "" },
    consignmentStatus: { type: String, default: "" },
    documents: { type: String, default: "" },
    warranty: { type: String, default: "" },
    cadFiles: { type: String, default: "" },
    videos: { type: String, default: "" },
    internalNotes: { type: String, default: "" },
    customerNotes: { type: String, default: "" },
    specialInstructions: { type: String, default: "" },
    tags: { type: [String], default: [] },
    components: {
      type: [{ name: String, quantity: Number, unitCost: Number }],
      default: [],
    },
    history: {
      type: [{ date: Date, action: String, user: String }],
      default: [],
    },
    grossProfit: {
      type: Number,
      required: true,
      min: 0,
      default: 0,
    },
    charityAmount: {
      type: Number,
      required: true,
      min: 0,
      default: 0,
    },
    netProfit: {
      type: Number,
      required: true,
      min: 0,
      default: 0,
    },
    status: {
      type: String,
      enum: [
        "Draft",
        "Available",
        "Reserved",
        "On Consignment",
        "On Memo",
        "In Production",
        "Sold",
        "Returned",
        "Archived",
        "In Stock",
        "Missing",
        "Damaged",
      ],
      default: "Draft",
    },
    certificateIds: [
      {
        type: Schema.Types.ObjectId,
        ref: "Certificate",
      },
    ],
    imageUrls: {
      type: [String],
      default: [],
    },
    costBreakdown: {
      materials: {
        gemstones: { type: Number, default: 0 },
        diamonds: { type: Number, default: 0 },
        gold: { type: Number, default: 0 },
        watchComponents: { type: Number, default: 0 },
        strap: { type: Number, default: 0 },
        other: { type: Number, default: 0 },
      },
      production: {
        cad: { type: Number, default: 0 },
        casting: { type: Number, default: 0 },
        stoneSetting: { type: Number, default: 0 },
        polishing: { type: Number, default: 0 },
        assembly: { type: Number, default: 0 },
        qc: { type: Number, default: 0 },
      },
      other: {
        certificate: { type: Number, default: 0 },
        shipping: { type: Number, default: 0 },
        insurance: { type: Number, default: 0 },
        packaging: { type: Number, default: 0 },
        marketing: { type: Number, default: 0 },
        commission: { type: Number, default: 0 },
      },
      percentageItems: [
        {
          name: { type: String, required: true },
          percentage: { type: Number, required: true },
          basis: {
            type: String,
            enum: ["Material Cost", "Production Cost", "Total Cost", "Selling Price", "Gross Profit"],
            required: true,
          },
          amount: { type: Number, default: 0 },
        },
      ],
    },
  },
  { timestamps: true, collection: "products" }
);

// Indexes
productSchema.index({ stockNo: 1 });
productSchema.index({ status: 1 });
productSchema.index({ category: 1 });
productSchema.index({ status: 1, category: 1 }); // compound

const Product = mongoose.model("Product", productSchema);

export default Product;
